apiVersion: v1
kind: Secret
metadata:
  name: ntfy-alertmanager-secret
stringData:
  #ENC[AES256_GCM,data:mx33kDU2O0y4lLvVA9LWRDQEEWLGxWdMC6AHI5EvDFtwJ1goVIHhq40porN2Cc23cx8FAReJVChMlFx4AwN7pIHADAeVgP/0D2pmfQIw,iv:Opq1knPC1AJxvDK49V467lLMZ/jUkWwup01bucRmswU=,tag:FAaJw+pBsgpjC5DDdlK/cg==,type:comment]
  #ENC[AES256_GCM,data:QHeWZo4vqzBU+Q3cV7WzrDgwBU1GYF89Ssxx3Eci4LtPHTyPvTDXLDqUeA==,iv:vapolf4xIVAobQOvz3dP49v05vbZNtHOyIhFbKnLE5M=,tag:kD/BfPB4dFxAOmjgtTDZyg==,type:comment]
  ntfy.scfg: ENC[AES256_GCM,data:62HDlNe1wwoH/K09sl+e1C3gQaB3+Ub6WCeQEBSQw6AFdnwf01VM1QYH+gUQNWrG1eovnEl51jNcgudypgS7GvVCp17jDe1PhVtp80kct3CBL4GpReUfNVZsxHzY0zjYnJrToA1WnXQDY9p+bF4ZN0t4fXrWhP/ZEHw15EnfHkasB3FvaxpqIltCzhSQVIv358vws+aoXMOI+h+jB7F2Xm6Ila1colrrdid4h3K8NOyOrMXxUXDqEuSxlC4=,iv:JnG/pYfpy0w1UaliAfSyDYtd82jVjZMonlU6G6Ezak8=,tag:/i1j81I40wVDx/SS8WXsoA==,type:str]
  #ENC[AES256_GCM,data:S2PVfE73b0tpTLFaw5fIGC3UP0ptl/MPxaEmSDitqAMoYgLUasbnPYc7J37T+pAKv7OQN7/vUa7rzwoHTGxVtHKeclQ9AbiKTLB6eLNpdyA=,iv:r0nPf9fNR8tr7k/qjkRsQWcjx2FoYGVaDKpbrIMddpY=,tag:otDeuiUysIrGF6OxRtqaTA==,type:comment]
  #ENC[AES256_GCM,data:a/fG+EHX/lwmTRewglkXkZWqgUzzal7Mpi0FouTp3jWnQ39Jz7HlAsIJ79ZVf3jHcBdlTwAT22xpMVXjYrjTn6odK8yQJ37Btw==,iv:uk30q/AkCYRzljpivg/rHEerOnM3hwdm8zFJmak1Grc=,tag:EkB+8zntraIqMaAa5pDGmg==,type:comment]
  #ENC[AES256_GCM,data:eAzUIygs8GyK8wOlbYI+ZP3t,iv:ulPaaJA6iXHf5hyvR9EUuRGwnvbCOeW9NqQ0PTKdh8s=,tag:HO1t4W0aCKoqLdWiSvEq4w==,type:comment]
  webhook-password: ENC[AES256_GCM,data:/c2Km1tyO/0nlYabQQwD4svxBbxldP8B,iv:Px5QTtAXGjNlsCfA4iDuuf+pPDcDTc323vh74iyCkNM=,tag:GZMEMpFsRsXBeTxjOeyBnA==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMldXR0g4alVOcjF6eEo3
        REcyTlFmZXppUHZDc2NkRStZMnFPMm14SlNVCksvZkF0VXdWaVhFcmhJYkxUcXFO
        eGlySi9LdWVPTkZVOGNxSEk1TytGYlUKLS0tIDA2b1N3dEJsMytaQWlkQkMrcVFu
        YzBmaUdBWmNpeFA3amZkRGwreUZwQWcKjOF0L/6cCOiEzQC6YRCZfcCNNdm6Zgzb
        pHoomH8gQVitDNueQEFCG+8NAyPtJbrJ9M3Nnl85femww99h0oVd8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-02T03:55:03Z"
  mac: ENC[AES256_GCM,data:VqXp03lsArFDlMeCSPsMwm5xizNF2FPA8RB2b7gXy6BOfguD61aYh96kUG+sje491VRDB/9DUtVEBxp1m2NOuK1YsEGB8Paj/SAey+MRr+B8PV2ZKcLRvcnp0FvG+v6XlL9PTmN+Vupzoagixlcq5gV3AuT5LBs93qeCbpz9xEc=,iv:jSWUpjeX60sUNnRB3oi6Y+jVPKr64I9J0Pun99CqOAE=,tag:QM5IfqkfnaZl8Ot4h+q0+w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
