apiVersion: v1
kind: Secret
metadata:
  name: donetick-secret
stringData:
  #ENC[AES256_GCM,data:DUplUAmJJZj7e6CmyOInhT34A0eygud81c/nnKAqGqKlm4DwFQ9RfHuMX5qud2SJycavdt/Bt0J2DrdZlG0ypQ==,iv:lJmaKZJYVuIuOfOsHfdfuGACcYRBgs7LHdteOQUwJ3Q=,tag:R2wa1uUeg9SrHbgniOYuyA==,type:comment]
  DT_JWT_SECRET: ENC[AES256_GCM,data:iLUaCZUlIs7/jsFp3TTcwhbOVW2NdthwmYGCog+vahQ=,iv:jqZq2gr1ku/po0eIsxU+gi6dKmq+4oi9y6q1aNehjAM=,tag:SOwi5b6KjRhTs3OXfgWzjQ==,type:str]
  DT_OAUTH2_CLIENT_ID: ENC[AES256_GCM,data:uGstimXei83HLeNGZIYxPj0eyz+SOkWsavd9MsY6jsvpe+8DbFpeKA==,iv:ASnxZuhVE2IYvyYiMdtkhcS9NlB8Crn2oh/FQDCew6c=,tag:nt+tlWgrnmg1+77XF3AVAg==,type:str]
  DT_OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:X5LRpgvH6pSpZ4NLW7WVfljIVpWL/rx5u2usPdXf+V8ZUyxg7nWrC9ISWyEIWD7g5N32L8M7F0homBaV7ouFErSxu7n2V8lFoxrpLYmAqUQct7XM7Jv41m/7Y0f/DNPTQXuvlsNfeAcfYKBRNJEea9ridtVE3nfFE4Cy323FXfc=,iv:tJhWZZEAYCiRjhLcxs/wa/GfRRoc1GH/90JNWwNRwQE=,tag:MkMdEFaIst5Wn0ieKs+pEA==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TGxmQ2NpR0ZqNzBnMlhT
        S0RId1BrWkQrZkkyTEhXNlNub1dPZ0N4SHpNCjhpenpaWk4xNklXdkMwLzNQYlNs
        dFRIeGJZWjJnNDFuWFZqa1lXWkF2T2cKLS0tIElUaXVzMllrMTM1MnVGZWpNZVAx
        S2RuU3pNZkVFTFdGOGVtVDFoclNVNG8KMF9U7nBH4UfqNoj5NRotGOb8y9kbVAoQ
        QV/dw/OqS5hVg++aQXPrYGgF2ghyT91tTuS9bRUK31hdBUjlupbiCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-12T14:01:32Z"
  mac: ENC[AES256_GCM,data:UeLuwb7frNE+fg8DbJHa948MhkvqYg2T4E7mMpMD0Q5fmcl4bTZT3lDgQVdoEeVnZHSAxTBeoYsfZYvHW+An6c1ENgETZZFRL4JNRiyJB8weQqY9RJgJ9EH8oCMLQQuhzre0zOi/6wpsq8qQXcQy7ftcMTISXXBhlmHptQmjWDc=,iv:nUunpb04thIEiDcZCsr4asvo63pqiy2kc7Ua7qf1L6I=,tag:n7bnGGh6HJN29fODI+cF3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
