apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:8Lyu4Bo=,iv:HU31v8LB3vvv2Qnf6+KEQRPoSfKPTRrPkKvZ5gjocg0=,tag:CJxXcHLhbo5ERSBZUkQNpg==,type:str]
  admin-password: ENC[AES256_GCM,data:LfenmvReQ+kPsF5WUe93n/f7QMLiR9daOoDLeTCq0sQ=,iv:NNFiLja+19vVcym1Otccljq7VX1oed/J2HLjy+Axuak=,tag:C5tiDKPKqDsyls8+lcu8vw==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidEovYnFBS2t6UXUxencx
        MjM1RXNGeEtiVnp1bzFWTVZ1RUpwd3o5VVI0CnRZbE9JZFpGSUhrbUhyakFXVzds
        MS9Lcmh2dVo4aW9uV1lEaGNQcmZIR3MKLS0tIFc4M0ZIK3lJS29qWE9RY05BeFRt
        TXJMdmEvdnhnbGpLZ2pTSUhHd2lzUXMKZ0LsxiV/MZiqv4jW0qSyl5Ce+WXmQ82K
        cQ5fb5nGlsOskI169XE6ShMz2WPcfFVZAMfMXGUg1JAy2xIihEa+nw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-20T13:06:10Z"
  mac: ENC[AES256_GCM,data:iMbpsER9hRJjYYI/5gkhk3+Wk9EstoHZyoqfgANuFaYNj9Jor+NP5DX1vuflMTymN7UC/kWsueGovWslWGzbyYVQl4uq1u/fdFr6w1cCJ1zsKx6iTCthdKlquNqBmrWue/rhSwtiRXiLyP31vknWJWAbOd1hBYhjKh0Bd/G+LEQ=,iv:pgBXMg+L9qT5WKXOICiALvZ6wPdVPqvOMWDUghIu8bM=,tag:oTsBwexusre4Mjw5WU0E3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
