apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:KPY2pbrokS5itvWN5pB1kudUUxxuQ4sSVs6JS8pqzmURcyqRFeLhsg==,iv:6X8d+FES6xrqd8h0Rm3YDxG2CFNiw6oLOFcOaF5utJU=,tag:zXhBljJzSwgqbwleDXev8Q==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:EfCvA5V/NrUc9WNu+VnOB4q/IedWSktvw5vcRzJKzyiUk3nbPh645q0t6rFl2Hot8wSu5s+cJ4ulnN8TizHlcv/a4srMANCIug596eav4OILf+TrA4Tl8/fS9p7urY8ft5z9LeMjyjFAX17tPr6iZbeCAyx8cD2j/LBiaBCvsQE=,iv:Ni0txn4uHZi3t7KivXTkNk/dH97kAs9VuIeZvGHquHg=,tag:PXH456uii4wDAbPH2gqw+g==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VCs4UHRVWDRrZFd5U2ln
        MW1iMll1MmtXbnJNcGdEYUkzWm95ZU1lZERZClVPbVhBQktKU295akNPZU5DcEhs
        bVFWckVib291STZ2RTFhUzFGT2tBZ1UKLS0tIDE0eGxSMGNMazdZRTYrQTdiMFRD
        ZkR6VXlPNWVtVVc5VE9OOVFDQ1V0RGcKKFBFsg8rTxfhS5RZJrstZ1FqsFT2rfqQ
        qJXMYFt4Bm1D/vHj49ZpzPbLPPT0lDcZQSS0kj7cVeNvjDuNyaYZOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-20T15:36:20Z"
  mac: ENC[AES256_GCM,data:4YXS6O1CAY5ev+RzsjFVkoPQvmzFQqs3K/WSnATeu8SrQjesrzETa5oZ7L8NFSH7b+mLNUXGseeP2GVy+WCeuP+WwlJUlhvLocQ4D7Kc3JJ8JdUV7DEQdzMLDTos75k1o2mJxjbV5/JZM9oKDGlE1/VXZjbm9KTNZefdIQhYu20=,iv:lFMcl6OrSsMFAbi0WckU020Jwl+lx+FCaHJyBQSJnjg=,tag:BsZ1xUjWCOqRfxzVrajxNA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
