apiVersion: v1
kind: Secret
metadata:
  name: actual-oidc
type: Opaque
stringData:
  ACTUAL_OPENID_CLIENT_ID: ENC[AES256_GCM,data:qZuFrws9Zwy4y8Vlkwbl4EKMEiw2iwCn0BFq0pubddmeboXNlBXt7Q==,iv:Yj/AuA7wKwh6acmc/gVASGVyEIAcS7wxm/zvD+JaaJI=,tag:rI9OaJI9jUF76GqJpaTugg==,type:str]
  ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:5Bx93o7fW/2K/QKtjJMr310hUiUZlPKusMRZ2JHuZrs/9NyvdnbvXUyf0nIXza2Q1Ya+gn+g2wKxHZ9CpTJXGN2Gvf5D1+xgssSDnizN8dfnUACTGrXqnAz4P1rAApJRFxnzkdA2K91hcoNgyckfXlgbaPwe8zfAiU3JeqXs/G4=,iv:w/qy3/9Ir/J3MIwWnlWbf2mrNf06XT2ZjEfio3yOzCw=,tag:Vl7IcbNVJqpGOw/NetLlUw==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eHlWeFJud292L2tqbVhR
        QjlKalZJUXE3ZlhvcCttYVZUZ3B3ekcvRndFCjhZOWRiZ294MDJkaGV0UjlWUVhw
        bDVQcmw1THdnTTB3Y1VGVWRSV2VhYmMKLS0tIFhQeW91cUlybDVJSmo1OHNMQWNX
        UTc5R2pjOWVLTXFDYmx6TCtzaVFzMUUK534EUBcGSlkQzcg7ouR6kJsAs39EWa1S
        5aGezGY0zQlcXxCFLs6rt6zF+GbmkmWJxyrvcFtllUDTibRPJxCGqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-24T03:26:33Z"
  mac: ENC[AES256_GCM,data:iHnfzwiXtMxitLTZOAygBx+2Pr/zj6Ms5pnrnuv2R3vJ5YIliVd7Jv+6Q5Ub/IG4NvFq7gcvE5LY+3+amfua/I4tdIsuI1bP/4aKwchS5DdL4YwtXe1N/oppPpvI1Op7/oRCYO1vPTQJZCpAfu7EOex2oKlp96BgVDLkTq2mN6o=,iv:FXc1/pcjcIRLEfmpf3FqYiHxxImY/xeUreUQ5c9+gpA=,tag:pUMAF5AdksvJqkRx1DH+eA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
