apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:PpEL0rxsw9gw1QSmCxUIgb+9wxJDRsYf6N/Oys7khUUpusS5qiYQgVmbLo6Dtye1oYkzWIk=,iv:gPQTdxh8HVAI81jIyad8d6TEqk+4UhQzdsQeJGA3t04=,tag:b1h6V/SWunt0iwacGoBcJQ==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSEg1cmZZZVFidi9wa3dI
        OXliZm43cElKRXVIbXZISHVBRG5IWVRDVzFBClBQekFncFowUEQ2M1dnYlNDUCtn
        UElmVTFzaHlyNElNR1NBQ3d5Q2VqUzQKLS0tIE9zbzF1UGhWUGlYM3dYVTU2Q1VU
        M3VZWjkvZEVvOVZ4QysyQitaaE9QNU0KrL+8jTdf1S1ediemEEzjUljpk30NztKW
        RwFWiwtB8nXMf1PhRtAlIdp/Gjkrb5YByetZzW916ZWrEnf3C8sAIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T00:31:05Z"
  mac: ENC[AES256_GCM,data:C5e5UgeWN1bMh23MYggS6tgUsJPKOFD3Nsy55yVRfdHwtrk9o4uaJv2gal+KtlyNgywpN2TodrGItim/B8rxt1ifMIlwVOrxbZPOrLHnUrVHVgTE4NoxKTFIIVjzexpa7NTef/Ult2UXESZ5Ghun3MXucpt/OJbHwh9aP+RZPXQ=,iv:esjnpjKiWZUg0rpRwYyFBb1T//lmLO3iNdgw0R3POoM=,tag:I/Ki1j6fGPzpxkqwqvJSLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
