apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:udkxxiqX/DiXGA==,iv:GrYKWQCjfsiq1LMAQw8DgrsJ1i/vH7nH6/HGEfvinhQ=,tag:DesOSeUGalfobqNBd3tbZQ==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWU1aaFBhVmdsWDRMN2Iv
        Y0JnOWV3cFcydnZBcUZnemVuQ1NFTERaTHhVClMvWDIyVGNCRVZoK0NFNCtrN0NG
        bFhSYUJkc2x3N3JGcUx4aWRpU0JYRlkKLS0tIE8vR3UzTzg2eHZOWXdhWThCd2p1
        V1pzNUFsRGNiUzZLNE8zcGZiZS9xQTgKu+O7iCky9mszI1lz12oCDobpJX5P01ij
        UIGcZ+QZJ/kjOsghfDRevgP4/y/dS8oszbszcuJx2ytr5Y11XA7cgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T00:31:05Z"
  mac: ENC[AES256_GCM,data:CJ86/YTZkJnsb8T6QXQD8FZMlkA+kAgoWwYVD3N9PegKczO/aRSzyPPyBK8dHWCRq0fp+rN0oaS5RdJfMUW8s1+nbK/MiK7AQKBevIuiwj90oaeM5rBXinf5LMDx3TTDCI01nOVG28EI3kA9mxCS4etTCaI+8XCkxNEMb7tFT4Y=,iv:BcM0loUn9WcBLkOap0KbyC2T029wvq1YYwvWIt8GCwU=,tag:p+f8pi6nHkmlGK328ScRsQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
