apiVersion: v1
kind: Secret
metadata:
  name: karakeep-secret
stringData:
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:32aap5LJmybyABsIeDpOJirVT8g9Tdm1EBX6rIzK3RjOgTWWiojhHe4knmwOwO1W+wnTonW7nCsL9E2wXjATlw==,iv:NNcJk34I8Kr69+xH7hVav8Y10o9be7WWigXGh6hWjXo=,tag:MjGXZZKwO5l4OM11z0ZNmg==,type:str]
  MEILI_MASTER_KEY: ENC[AES256_GCM,data:QjlXtxNMjcICA/bSRcfaAQDjCyT2166dLmvrDTKcl6CM8igLHekzusATmT00gl+q/Cnxbp069afL3C6Xsc2v8Q==,iv:sUbrVcctObnxn1O4Db7J0fqM75QR1wHyZBvlAb4WpFI=,tag:AJEQBy1UAyQhLz9LqVYvYA==,type:str]
  OAUTH_CLIENT_ID: ENC[AES256_GCM,data:Lcyz3mJ83lwDvM+tmvYdjTBK1T3/c/GzcP4DMeyRYB8o/4jsM2QEvQ==,iv:r1be4AhfevapOElkR+PuNHoCYelAW6RFvCX3ZVBStgc=,tag:NQP1sY55ghKjhPl1wdVHdg==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:xLg2PD5Wx+eTYaRWpPjPFjs0C4CIYUdjEQBo1iKtsm/PDEox1Mo+vE7s65yCK/HElCBXh2+KAIMD8BdXDlVFqzvWpE2cW1OZnoIjRHcuOpymhq3ATbZztyAnrX/lHqdtcc7t3gJ3xzWVtRKUOjVE5P3FVImiRWab+SuKz+At+7w=,iv:TZP+IqK3nLQczM5W+r/to9BAJQAs+2y4JMZ3Vgaa1i0=,tag:hCaSZpWfXLt4uXMOgkywBQ==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQ0h0VjhHN3h4T1B4eDZZ
        UHo2blFHeU5ad1JwNzVQN0FCVXVEbHNSRlZZCm1iaXVwSEhOMGFBRHJHa21Zd3V1
        MElteXZSNlpacjR1RVJqUEhXc3orczgKLS0tIHdNRHFXckkxWFFGeWVZNVVQQ1Yy
        Y1NIRGpadmk5NGUxZERlaVhxems5ZjAKQrhacVRwRi98caQnrJ5KVqk4EebNBGsi
        z7AB76IkY24y7Bz8hrGvdHUh6+mbFxiQPH4Dv1cudi1n5P0xzYezsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-12T13:32:36Z"
  mac: ENC[AES256_GCM,data:gwd6+d8JdgrmmJ8+g2+Nc39XjXZyg/AfHJRrJ3/dJOlREPvSoqoYTtJdLeXumXZPSELHKWeDW6JEi9m7jacahmKpad1gk8EsZE0i/Et9s64fug194cunVEZFVJXtAX1aTK9y0lsEZ+NzNM3JlZ0MUnq92pual7qCI+3PA/FUEqc=,iv:2aznyks0ZdonUlNbRyM3c+amA1ClbRcLSKhTVDfuIMg=,tag:2RGlhDrtPmxwEfweGbnQ4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
