apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:C8OE7QoedAxQHcylXXabX8kcGJmd0WOwIJPv77c4nXI=,iv:GBK2/ebMmID/gJDebB3LU4zSZlHHZSpvbCB0iGD294o=,tag:N9qs70CGt0KNTQe8jy/Ljg==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcVlOUmVJNElMcGxjeERj
        dmR6b2t0aG5VbTN5Wnl6UUpxZ0ZETE5LQTJBCkF4R0o3eVdjWHdRQ3UzTmJnMldS
        RytDZFlRczcvb2lhQ1VmSGdDS1p6R1EKLS0tIGpwaGZHcnZZNGFSWTJOZGFZREtq
        V0g0WkFUcEI3SUVSenMzK2VnSE9aZ1EKCCYiqjH8gOWBsGBKWl58XlWGBWXbzsxd
        B1Cwo/z8DA2UjAWHG/+hHWOF5hVAhs90hOOoot9rGzPHtgu5vZDGzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T00:31:05Z"
  mac: ENC[AES256_GCM,data:+UfhSoTCbOjxWTj3u220HGoOpqbHu+eEBGwZmEiGi52fxKA9++JQroRaf1PSIQ2ggpy4OKv0MQ7aPCr8KDJOReEWvxD0X/IFsEY+ug2O0HQuuqpvPpCd82d3AbPvYszvhwNnj85VDojpSDIsJGdcImWbsZTgy4Vz0QogVVhWkGQ=,iv:SSpsYMSVGFEazjxtXhUzqxphB4bIAwHTYVH6b9uDQNM=,tag:MoJw1oGsdtnnr5rPRrjaGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
