apiVersion: v1
kind: Secret
metadata:
  name: smb-creds
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:nM4RIM0m+JzS,iv:1PQazXG+ST8uzpT3boAqymRlyi55RMMtDehvw3TS+Qk=,tag:ljPAODJ59gWJG09PoPp6pQ==,type:str]
  password: ENC[AES256_GCM,data:lOdGzcP15koH,iv:3gW154Wp8J4VklWXBTvWrbMLKqWZ+QuJ0/7KSLumDxk=,tag:fxUOGdccT8Uv8fVeGiKo+g==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dGQvV2N6Z0NjRld5NGhr
        OFZNM0c4VHE4TFEvTTBQV0NETFJ6TjJQUFE0Clk3cER2aGFLU1licFR5dzBwSUFC
        ekxCSUVMVitQUE1wa2lkZlZQNzhIbU0KLS0tIE5LNzZoQTlScjdST2pkck9MaEFt
        cndqQnJzUm16NHdrb1pqRjRkSmxESzQKFjlQyRNYrtgpy+EKNyG6jUYCwNPy3QFG
        1jmTiWscF4V5535jxfOzvLuaKFZleSz1cRPOAzUe1uQIIUvLPJElCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-20T20:47:48Z"
  mac: ENC[AES256_GCM,data:wMjZRyjSj1Fp/EQqpDt4qHo8fJme5omKAxCJ4+bJkBFN9aIa2jLXub4S7GfxvIzWO9OzE/ZTUlEB7Af/Sm4lfnkH+iQ9s5VjjiQCbBGNQHNGj7W8YLCmC+R+XsuTyaZWZUWCckSrQyL2QaMEol1H/oPflAvI8Nh8chb9M7pZLfU=,iv:4hzX8PlwJ+Pj42b7/toQq36nCK8vQt8Af9lNXCRMpvA=,tag:NAGr5ILUwT3wE60nfNlYAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
