apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-vpn
type: Opaque
stringData:
  #ENC[AES256_GCM,data:DcU1/sI6t23iiYVXLO/ZS9fKc4HH7NQ5tOODPUJVnQVHHnBVsu6jk1AYqMccY2gFIeivAWxoCUrjk3JNo4syZyf10G2a55ffpF8AqSDYztNn4TsjaRQY7+uO,iv:0D3IIsGtDZxVtvVulFvQqYHFklaDa5CZux+sBMhlKec=,tag:mzHzwxqrsCxhLkhcGTRpMg==,type:comment]
  #ENC[AES256_GCM,data:3Nxo+2bJvC0qYozjianTuj/bgMuCtLcaT0EIiJIoDWJ16NIJlve7XeP2UyUEjnHetTZvtCnHez0jSogJ34Q=,iv:CEnuVtC1KLkzwdJKlXgxPq/NzGwrALO31kwlfJuA91M=,tag:aW8ZXjVoAkelLh5Fu3NNAw==,type:comment]
  #ENC[AES256_GCM,data:tPQgu2oRJLpn2LDVXeq0909kMJ78k7+Erf3RG6mqoX8os814jtpYI5GDzXPWWu5PEYkNReXUJPrS2v0mY2c4JCsD1nxY7/NaqNhDx9UH0h4LIXTVeHGBkgJvqP1IyA==,iv:fezCm78s0zI+DFmy2IqXSCige9//fBQT0kbbOHJTLhg=,tag:9dDBsrjsfXAw+jMRW+X2Ew==,type:comment]
  #
  #ENC[AES256_GCM,data:B1W7nlwYkh1oYz4GxwC/7MGl0n6jyXBo6+xFokeQtQUE7S+SzGcFVlatym/FA/kehEPo2LIfsXCctuiFbIVgqXiClOJIEUd9ov7Ss7ENM9LbSR/ki8eANbgxfX26hJo=,iv:NBv21wJgTME/aRUtw6RGjEv9ed9NjCwp1YhJPZ4MvlM=,tag:ZW3JUfaX+aZOlpxHgkccNQ==,type:comment]
  #ENC[AES256_GCM,data:xJjGeOO83m6uodX/LbQoJi9K1vrc6ksLUQQC0JdepSpA691xBb4CKguNdICcxlEQWkvOgwP6qTblME5ddnQwOxkCwCtDfL6HXkO7bNf1/fR9sIQBjg==,iv:c/Y/6aSUr2qT/6IdjuXuxJIcvjPTPP5zrh2UddxFJ8Y=,tag:PhA5rJK/CHeJKWwCmb+lxw==,type:comment]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:yWoIYQ7OfiZLlf5JvKVD4+E0SjUWcjmi+5rLv/ihSf3H1uBHuN29y/UQ0q4=,iv:UGV+30VsDkQ6hBcXtEQAvcGmJHk/EY1KhUVHEWHd7gg=,tag:yoeFomUpozBjd813fcdp1Q==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:suyhlj0BleExz6I7,iv:emI/oVSwD0sTLMyG/27S0nIDKOBg+6/L/0mp6JINWeQ=,tag:e7cUqtkE0QtZ/jvElijMVw==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcXptbjBqN3U5NU5kSXBh
        T1VtSXA0ZWJHaWZYcUtWbXpVU1VZeEtaRENvCkRmMTMrUTE3dktvaUJiTGhPNEU5
        Z3RrSU1GYUR3QVFQQzZwWitCQXdmUkkKLS0tIDhjSEloWTVBNzZuZHAwQXBsTTU0
        N2R1RkJ2UFYyVy8xRFpuUE14eXdpajQKcUQdmmcLr8U15tep+flUXpeBrqtE961j
        T1g20u69uOVO94Rv6YQrGMKZxDTANl/1jMiveP+fU9Q3PIFHTUUipQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-21T12:37:53Z"
  mac: ENC[AES256_GCM,data:kghFvka25Ta79TvPELhAOb2Z4elCAIq25cGPssV7G3g5g4mky/WPa/g5xukqkN70TIT7u6HOPzQN3HcU76KYcQPZHHvdJgsq/kiSfA3IN4c5GFXXZOIRmSK4qkfp5nHbL969eylPU1J/B6/0zNO8VBgBANsXe8/zr/XunCkqb8c=,iv:/Ci1ohmdbEvGfJ5o2yw5NrUz7Fk/oacu3J90GSldvBI=,tag:htNGKxa4LqZJRPlQxrGqYw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
