apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secret
type: Opaque
stringData:
  RADARR_API_KEY: ENC[AES256_GCM,data:I0DhzzD6jKNRQwVt3ElTARBNjh+l0q9X44ynfixlb48=,iv:bowfkO+dQtW7XWi9KxalGkUFmDGuzhv7fbWnRcJNrH0=,tag:aEH42uZSMOM5QMM9rNt0zw==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:8wWlD2E67P2iccvtFqORVIqAGF3gWxHA6Q0iAfw7dTA=,iv:wxNQVmZi9U4UKopZIELClN9AuPZcLB7HTMTOj1Hv8ys=,tag:4hfbbQ03d5+d3NPLCuKq4A==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Q2p2VzFlWkd3R3ZaRjBM
        dDlZVU1qcXVOa0c1TzZOMzJVYUJsc1RwRzIwCmpFQU1wTjgzaW5BQkdtT3BCQU03
        M3ZpdkdTQWhXcWU5azZqS2F0QmtlMmcKLS0tIDBia0w2NGZYVEVubVJGbjh0dWFv
        MFk4VlZTZGhOaUpMV0R6Q3p1NHVOMmcKsrg6YWZangVhECiiCOhOeEpTtm5t+BYf
        FZyaTkTUr+iLISGwTEJ+vZgiStaHA2nQeGAY9gVaLxj057NEPE0xaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-22T03:01:33Z"
  mac: ENC[AES256_GCM,data:yNVSeBH106YjEWEDrloexGCoreYy4ZI6Cq5JJgSVZ7cn71FcG4RzEe1KUeUX+ScBY4sLfktqNspC7bWDqQyYWtEil9X9XV39GTsZL/mNxisHpFJy+ZDp0jI4jt9aW18+fn6ox0z7oydWC/8lJMmG1hC7VWd/zVa7E4gzfcD8JBI=,iv:85V2tmd1A60sguGrrgCnyvoVnOS8nZSbS/SZRzFydNQ=,tag:I9QN2CH3NOfqOuvlinEuUg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
