---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data
spec:
  capacity:
    storage: 1Ti
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3.0
    - noperm
    - uid=1000
    - gid=1000
    - file_mode=0775
    - dir_mode=0775
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: media-data
    volumeAttributes:
      source: //192.168.0.25/Videos
    nodeStageSecretRef:
      name: smb-creds
      namespace: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: ""
  volumeName: media-data
  resources:
    requests:
      storage: 1Ti
