apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:bwzVdgBIiyhP/BOfgf6w8Xpp6UlY1JgjH0+hPwsVnH4PsewxcevK55OYsh1KzkgY7NB9Ten9tAJUf6iSDzlQr8YAmi/zC1IuI3RuBm7qkwE=,iv:rp2rI/cpEUh41w98i5PEH6SnEDn8MbzIKz+NN74OYsE=,tag:Mh9SUYP/3EQQMoquOZplLQ==,type:str]
  AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:wq6dlvg/kwdaoVdNwDqT1V2Mgax6Ae4m3A==,iv:OaeLa1QhpmtDk5LYDQwQe7bBqH4uKlZmLVt7RJrtq0I=,tag:hw6vSYKobxNvlj099Q3Tdw==,type:str]
  AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:iKaAI7Lsr1R+uvSUUP2xpCwZCfg1ilp3ugDev2m8Cys=,iv:RzuLQOwLmU+Klv6UodVBWCKh6g3y00G72UIddMY/Jyc=,tag:57klUyQhbPKss4xOu6e66A==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQkRZdFpTQTJGcTJMNzM3
        amtxak5WL2VURzFDSDduQXp1dlJKSzF0bDN3CnBNUHI0OUN1MDlZa0UrWnMxL1NQ
        bGoydE8wUWhKKzRSTlkvQlhBREZwdjQKLS0tIGN2aXM0ejRnaXV2YlZQMUxyK2dz
        RVNkNnhCeUVOUkM0a05tcVN3Q0NwelkKWtVDMORME7775473K/QJDd5aSxgW3oCv
        R5g8D7xMjA6EmXCkcJ4Bf0N3HC5A6ZEm9lgLcfLhYqfJoJR2thXsyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-20T11:13:25Z"
  mac: ENC[AES256_GCM,data:YFKXsJyjAlDZvBfVHi+LX54+d5waQLr6/x9aNvm0Ao4LXmMwoEYYWcuBOYtnUUOC7ZG9pMxt4d61gJ1H0VaxX3/c1EcJO8qrUbDFsaTQqIA76uU69dPmO78kPXL7OrO1RgwjRs0Otpj9RMl3nGrSY2JvpKI9S+EwVSvBWnRUSVA=,iv:/hBQGI1RKoNvbJBi1tC8NiksH4z9HDBZndcRLKyQQZA=,tag:jMtQcLfJO8dYRqVgdAF6pg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
