apiVersion: v1
kind: Secret
metadata:
  name: isponsorblocktv-secret
type: Opaque
stringData:
  config.json: ENC[AES256_GCM,data:i0uQ9jlecDDxlb++Wrn7R/SmUc5WmOdq/k1KXDWfQgprvr3Ijq+Jk9dE8afEgzLCpGXQFSXFA7xE71FNfJXHiIR0Wld2vGDP33KXy6bnoqn0VJwVnKOmkyKXJHnTUP17rmLTpKpfVfPUsW2s/6PCxvoiO4XrVJpWf2YeTcun/MyAXaWULf4W/sRYu4/CRx6H6W4ISIaSFDrrsefS4hyLiIz7hdhUHwuiTwSdoEZ970+CWpOK98U9efi5l64gmPTNz8Q62fPLJRNKhXhZM9u1sU4OKdD7mvQBpLyjaK6NYuuCihpuqgrXTXsEZK72FhhsjjdUSRRSoErmi5CscyzACD6yCC5+O+uC+3igMQISHx2F/83EP/DKhJek0zQNB+rpZULazsEvMZk7Y3JcVbF4OpfSPox6KiszuKbycgUOX8svR1G9a/n42+Sw3WeINHV4JOvk7tfYJjqzYnuEtRvhK4Rx6n8c6VAvW/dSNuixmKuXWJIwMYylnoSNrHhlrJOUChYAccX84fA0R3ollshsVdL7CLKuPkM9yBi8EBCVTrs83cAvFxX9zqUBLOpDbEnL0EqR2vP/D58uH89F/Fll2POrP+uSMw==,iv:BuqNCqcOUTUCqIK2vnhas+/eJ+PmWsEzdDjgUrux1lY=,tag:hUJBlq8KNXUrDHUDy1RFsA==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMUpFRmlDQVVCWjkrc3R2
        a0Q4VE1KWlZ5bm01S0pVbkMzOVJhYWxrZ200CjVGRFZDVDhBWlNCbkt3K0NnNUVX
        VVZhZWpCSnBuSjNpV3hLRkN6SFhIR1EKLS0tIFc5Uy9QelRFN0pucHgyQUF4RXBW
        V3U0RWNjZ0ZGQVdMMGN2aGV4S3RvckEK8FY+yuXHgc1F+P3IYS5twlAdPV5VEyp+
        3q0GOtNvp388XrWU1odpTwWQ2A/+ajcdvovkh6KP2QiChNoWEIT0Tg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-07T13:26:07Z"
  mac: ENC[AES256_GCM,data:RW7xzfg/Qxet93TYw+jpL+/zJ3MF57Y2QxpOd7mPdyk+08CiXOZChEFA3/2b95t616s5SHPiqMf4xKc/lxBtaW38/dQX4fyH4WCyAk09YH1+aVNVXguhYYUJj1lmwD+ja/rTaK2KtTsCar/2FrJ7OQ4O3Z4EkuT9wqH8pAGRzCo=,iv:bggZ93onJlNy88T3un6lZBML4D0OLgMcWgPq/bPW/ok=,tag:dhjL8Z0v/esEMhK5Wm2J3Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
