---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./actual/ks.yaml
  - ./echo/ks.yaml
  - ./apprise/ks.yaml
  - ./homelogger/ks.yaml
  - ./homepage/ks.yaml
  - ./immich/ks.yaml
  - ./kimai/ks.yaml
  - ./lubelogger/ks.yaml
  - ./mealie/ks.yaml
  - ./ntfy/ks.yaml
  - ./rallly/ks.yaml
