apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Ex6KhPHMLxldEbVnY28TsRDVZh3XDO66Hz03MXruODL18j3c/sTAn7Z/ZyPXGqAllw2Vp9PnxIwAVNlD10qzHxVJkA3EZYFOTSLCtV43/miiqN7XhewIoZmlaf0mMQLbpCL7E6VqcYrgaOtHt3gwWGxitW4UAs5qE8Trl8YxO7Il7KTyhj/DAXthIirYb71A4qFM0InPTmCOCbGAIF8xTmFU9YqsthVobdXWzxD4TMPf9mPf,iv:4qMB+hvuTqqS4heWRUcwsdE18DGtH1gfK+oVQuDxWos=,tag:isHIftvy+GH3S8dgzv1lpA==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UVRaNlZ6S0F0Vy9GcVhM
        TUxrMWxLN2hSUmU5eUM4QnBoSDlCNDNBOVVVCnJzbm1RR21iNXdoK2kzRDZtWFFy
        MjNkZ1NSbEcveFZEdkdiRUdhWWxVTHMKLS0tIFlRRXAraUZMMDRCcG1OTVpRZm00
        TXNkNUxJeFFBTGRVdlplamI3cDl3a0EK2EuFmnfxdHvNi/EftszefTQm2E++au27
        pgJZ5qqaHXbuZq73/yFKdX5WBvGFxqjFrN5fQMy/p4aS/x81HGdBcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T00:31:05Z"
  mac: ENC[AES256_GCM,data:3M5+m9iUJana3BHJludvkIGDh2JcQcxqCkrebQEM9sbHX4eDyiFEYBANlZo1rtD61rrxAqawTXLlaksRmR2mhJ7PlXRA86ckRhPJH9cbdx5kIRoCxFqn5TrGAMx+5ly/IiLBmbBtvoGfALhHY/X8K81uN2JbhN/EoPK+vl/uWwA=,iv:ukHSdfF+IDR4Bc5NOr7zbv+LiYwwxxUU8axvlLVyHIA=,tag:OfDb5nk7M/yZbJ17/SS47w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
