apiVersion: v1
kind: Secret
metadata:
  name: kimai-mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:ibgp0HEGsusyH5B4HWEPj8nXVLx8TdxrNH/ad/XiFNcDD6fOM9/SXph9MAtRNgGn,iv:Vvn/ABMiAPZXJA0bZY7vYumkUvwjbzAurrrU9CsjIrk=,tag:GAa1/KsuX5bVGwHd56sSfg==,type:str]
  MYSQL_PASSWORD: ENC[AES256_GCM,data:3v9ft/7UpnSN7fJbt1MNCINiEVWsoyVHxSF8DGbXd+9ISR7B1/0vnQT1bACABRJS,iv:0RTNcdW5nPQY5cc1BAHt54aqQX5AR3aYamZNpiP6U0w=,tag:A1hu0uwNNItRY5zaQGaIzQ==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmelJDUWZBanZMbXZvTkU1
        dzdlalUzRFNhZ2J3TnFJeEY1ZE5HczZuUTFRCmhLUWRWWlZpOWdGRmNXM2pvNlY0
        RDBrc3ZYTFhDeGFicTMyQkxySktMNG8KLS0tIFYvcEtwbmR3dXlhRWRVZVo4SFhx
        aDEweFpXaHlza2tmcWdmY1JvbjE4Nm8K4XK7Jaq3T2f6wdEiQ84SGHnfDQrWxpx6
        Hp1x0kwEytmQ7mKpdcWiyh9oVFktyGZ4U06Lq9A+6zlU4+Y1aMJTwA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-24T16:17:02Z"
  mac: ENC[AES256_GCM,data:yboA9vDj4f5CX/o631o0A9DnLu4uDn920hoZL2gDGfe8G+wyrbmPAaOxpeNJOyt+/gQFrERoHY/EN+/ijllQdr6ndGuCc6+ifOioLO/VPosZ9VO8oJFKxs+W5ee9xfzHtiw2IBakeCbBsRV3H00ACM5k+YMZL6xY+QnuZObk4Cc=,iv:BzMt7jeh9yp1PVrRudqmdF91rb1b+rVCDux/1Ujw9ms=,tag:S9f5wCllS94kovi8swEHsg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
