apiVersion: v1
kind: Secret
metadata:
  name: kimai-secret
type: Opaque
stringData:
  APP_SECRET: ENC[AES256_GCM,data:H+FAMMWlb9hS0o79mA6pOuAFJ8zX5uxfS1KnyHJ2AAMvo6XtcpYsMnSs9jTRu8Ngfkk9ZFNSfVeX2U/InDRrkw==,iv:s+SAtjmNlu8LDIqSmj5IKwT2hqCLOVfO8h+nzkZpL8s=,tag:qB/Y3E/E1LWomlR34OmrzQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:ima7R/BB/QPPuByqT2Ieq3E58G7EiLv9pV6K6hZh51EzRCfuPoQGaKOF5a/0cDcaXUq5ClmsSVPE8cHnA8rkKWclNhWpXlnYzpThOXXMA1xTQxxzvdL9MzUMaY3nkY9diqcA2PA95A2oygYeMsSMGvdkpHnomzXEm1fhCsGq/rFJ+tUIFQL8Fk73uLi4eCAk2oZG,iv:ifIEBXQs0GXbIOHmy4gjkQQ4lbolc98tpeffY3Q/KgE=,tag:6gPLvYYbMFOSAGDL6kQYTA==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBod0VPUE11eWpuRElma3NJ
        K3BGZmIzckFjSDUzOGdDK09ZYk9pVDJjZ1F3CnAyaVNIK0k4S2xHSkVxTVQvanU3
        WnNkakR5NW1jbEQvNmtaQkJleHVQZVkKLS0tIHFqbVVRVEYvWW9YQTVtYThvbmo3
        SWkwcWVBOVlBYTB0Y0ZsVmMzQnZhM28KOgQy+u19SYXVWkplzKMm8zfZHc9BPEci
        wvRPPyk4LVwZYfnXIRv6iubNC8o169d9uyf9tKmm3JGNvZ2WPqDYMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-24T16:17:02Z"
  mac: ENC[AES256_GCM,data:BsOAJ26PmL+CnKJfSvneknVnGCgGq8wMN1JhxY7uDfuanDKbgmH+RGtw6thtFkeeSIDWCLC5gRzqUfYG4SBGFix1FYHjLY/QWVwWFppd8e7mfRNmuJSvf8bPE2KyfsVfSFialWs4Vsn64HnhwN11eOMEICIsKAoiG1K8zo0XNgQ=,iv:zthb3M3VGX5K8OnA2OvbpcN8JWqJijdjdD4DEO4Nvew=,tag:TnqznZoUKQzi44za3UcKEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
