apiVersion: v1
kind: Secret
metadata:
  name: tubesync-secret
stringData:
  DJANGO_SECRET_KEY: ENC[AES256_GCM,data:gCvQSqy3dWH2dtcJ64DK3h4FBtdZJuFrjNz9cWukmjLWVKcnouvvSChBRBqtZoKwiS6K2XzcLwgUHCbNigHtXw==,iv:0RaDDycGVVJPjS66+uU8f/Cd8UjrrKttwWVPHt67lnQ=,tag:2u58fVsqaeaG2M+jgi+R7g==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZlJ6a0V4ck4xbDhQZ1R0
        T3Z5YjVneHJkeFJjbGFuRGdmMHhidXpsdDJrCjI1NnRlWlR1eHY0d1JnRHJ4SUVn
        UkE1VlNaVkZTZ2NkRFZNaCtQUzJJWkUKLS0tIE0xWmtWaDBwSmMyM2QwRXN0VVl0
        RHdNOUxrcmdaM3dHcWR3YU15enJFaHMKgQG0Xa7etfgY+QyyXn3JDUBOBR51qt6V
        3eW1B5K744WlZGuU9tdUfhe/5tSlUvhpfWFb/DoHfj7P9nMoO2PzUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-08T01:39:29Z"
  mac: ENC[AES256_GCM,data:EevaCkQLiTkEOXyvsZduE6qPCM8558o/wrplPJPWeXo1cenDyVs/vkOkAov0sL6Z9xIdrG6XBtkhWM8hl+un1OPgYipOVz6BcX/tV9slwgvQrU2vATAerup7DxbGgNssTlEIGhSGzmezd6zzLhh/+0dQT8st1IciX2vqEi5UnIM=,iv:crYhgzEhbBH4PX9kkhwXHQ4lPD0HT5T3Z/YYqaNNtqs=,tag:dKEDEKag7RFsuy6jMgx1/Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
