---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sportarr
spec:
  chartRef:
    kind: OCIRepository
    name: sportarr
  interval: 1h
  values:
    controllers:
      sportarr:
        strategy: Recreate
        containers:
          app:
            image:
              repository: docker.io/sportarr/sportarr
              tag: 4.1.0.1110
            env:
              PUID: 1000
              PGID: 1000
              TZ: America/New_York
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 25m
                memory: 256Mi
              limits:
                memory: 1Gi
    service:
      app:
        ports:
          http:
            port: &port 1867
    persistence:
      config:
        existingClaim: sportarr-config
        globalMounts:
          - path: /config
      media:
        existingClaim: media-data
        globalMounts:
          - path: /data
    route:
      app:
        hostnames: ["sportarr.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
