apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:07vl5cq+y9SNcFmoZ4FkfSay8KwKh5I0QbWRGhijoZZPSy1pmqogbUoTlReECwznZJFjs8E=,iv:F/20Rgi/y1ArJ+LFTzJH2+6p2K2eel0E4D/yx3m/e08=,tag:zma4jvLqa4tP6sbSZojo0A==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM3VteHBodkxMQWtUL1Mr
        eGtWdVlsVnJNTC9LYzZDRDhGU3hkTGtrbzFVClRZcGg2bFZBSGR2ajlKc3NwMUNn
        d0tITHB6cmFlbE52MmE4UXVUYnkxVk0KLS0tIFI5VzVsSCtNL1g0cUF4SVFTMkVq
        cVFtdmFxTHY0MUpITGE5WVRpN1grSXcK+Dp94EUPIkn7im6h5JO9hSUh62cTkCvq
        PN0jYSU7XArkqbpJvtLxyMxr+b9RukbHZgcclxCVEkMJG5PA5PZ4BA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T00:31:05Z"
  mac: ENC[AES256_GCM,data:K+nqXchbxcGc7yAb0GvUw4cXLY677zcer70Ga2FVwFRU6Bw/DV/1QMH3Wv0y8s2lGb9PcbQWLb0jDbvA89fz4E4HzinYumJtMnZhmiyzTXhfIbxmQHyC8bcMmbH1k08ESVvEuiy6aFMO4udfTaU4KJSy6vREmbSNZygv2EDzetU=,iv:qNRu75cPFwMFpehhCiqTlm5AiQVNsHdshPOuMnh3zRE=,tag:wRBVMaJQyIC/duMWPhcojQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
