apiVersion: v1
kind: Secret
metadata:
  name: adguardhome-sync-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:pcApCN/d5BhlQh83CP2zF6jikUiEcUUTnFIKvMeqdn5+8wTqUI0zzXCkuNwYOOr5sEt39J3F8eQuRsrGRXq1BFLp0s4=,iv:E/Floy9MtBzToBKoSIxszkvI+pIgat6pdjFSiK47jqQ=,tag:0cQrTNyueKGGiFbdKGnkJg==,type:comment]
  #ENC[AES256_GCM,data:Uf6a2JbAFZMe7GqdwYuYpRW8JWgkSD6K38mqorGNIuSWmCTDTkNxtnhEU+MtSE/idVAposiYQis+AZEWjmQSdMhX0PK6+d995Hc3H40txg==,iv:gVw7ZyoCSrtTtPyx0dXIR0QOaM0GfqtrMf5VKYBw/pE=,tag:JTBxj6oA2OPeBxhUtKFysw==,type:comment]
  ORIGIN_USERNAME: ENC[AES256_GCM,data:EgYOCQ==,iv:4CjKL7fNrinywfHRsVq8O8m1md6U3zUp608yt4Z+hZ4=,tag:Uc1JqFWc0GoNzZSyE2GiPQ==,type:str]
  ORIGIN_PASSWORD: ENC[AES256_GCM,data:R14inT0GHnS08JypPWXL03Y+TmcpY5NLnzH1FcQ8Vxk=,iv:sisKriPb71yIMXV4zoj5d5TYtimkZOXLSoh403yMz5Q=,tag:nnqmpF/ADmev/Go9m9pzlA==,type:str]
  #ENC[AES256_GCM,data:fQZgGvX2hIevCqvqLWiEmGDCmjZ5jWFliGtUHV8eBz4NvbRBEbtwCAXRiKdb+XLNudYWCyhh+FF9S/+NpOY7prfabe7h/RlJxcpEF4g=,iv:zcXYHdAksa4fo4nKKUv0p3AkgCKhD1aGU4IDPMZShtU=,tag:TE/oRAVBxHjKqLSloYljjw==,type:comment]
  #ENC[AES256_GCM,data:9B9cHB8zQKoZZ1hvwTYU5mcHwfOKtRelnG0dXep7xc0nP44C9KVucwbzBOPUcn3kUKLmgnF5hAKZQFqTPks+WEqk6k1ZRR2kj62kuiCr,iv:W2HEdDivME4pLkzXd/ilgT6U/+Q+a6yqM/t/FrueOg8=,tag:YuGSbD4r8XP4DUdMy/sjMQ==,type:comment]
  REPLICA1_USERNAME: ENC[AES256_GCM,data:WT7zf/g=,iv:2Qz4EG7ObpCSJP/3+yciq9Bd9wWV05FUYd56WNaeKMs=,tag:4g/oD/HOoU1Xh6CLtFfk5g==,type:str]
  REPLICA1_PASSWORD: ENC[AES256_GCM,data:qIaVPriCoFJYmg9dd4S+8AypEdSFNvgB5B0mCeAL5UPwP4GaQlkfwrDI6aVSbksA,iv:VSIw+/i9hKKXV8rlEBjkNTMu28GareyQBrAqCsoC+XA=,tag:bE5wARumWrRLfvXtniU67w==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5alBRb1lSb1RpbHdTWkMv
        YVIzUzFjWjBlMlRsZTI2SzJjSVZsVmNUQ2xFCjVMbHVCZVgvTjZlYkc0ekl2Ynkv
        REVkL0c0NDYzK04zcXUzVmsrQnpFWUkKLS0tIEtkMzgrbnJPMjdSNjZyMkszeDN1
        aHdqTkZxK3dkWk5EaFpEUnJqN2xRZlkKAsKOe74QQMb+GaBaiW/H7zj5Nvdf/mfm
        K5LDSbhEmy9pHIZ6fyeDlcQTg5jmIoZ5WriR0UihrJ30rn5ItVCDrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-24T18:29:01Z"
  mac: ENC[AES256_GCM,data:A6KA5FPmcPnswfNzuNUyx87MC+xjjWkIp0VGnVpTFaO6cDrSROlh3eYkfccd43n3EXCYhrL1KoJsm9bp9X09H+CPiLsC3LG2zh1TJYODTSLKrL30qJ2l3RiduQSrLTgDt25wbEifRzgP9sDEaivXdp2Pirgdi8M+vrO6ofkuAi4=,iv:fbz66HqrrpHZaixCUWcL2i1pAwhQTPbQUlrxu0I3ZAw=,tag:14C9IWimkVmZhNxEE5eLoQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
