# Authentik OIDC client credentials for Mealie (provider slug "mealie").
apiVersion: v1
kind: Secret
metadata:
  name: mealie-oidc
type: Opaque
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:6ToWchsS/Vbtg1kgR2FZM8cv0Er3tpiKeiUCaKgcdF0ggSRYlNRqGg==,iv:+HfsgL/md4JrInhcXdRAieOCLIO9dQyHBR6Kag4KQeo=,tag:hCapbu/EeUdLypiqNLX+DQ==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:+o+1dpI+uoZsTUnW3GspIjNYPbbW/Dg2DB23Jf1fkAssG5gsJdsAik48ynrXdxvLhaLvMeDmNahfZ+kbbIrZwAzvSM0VnqOt+MvBfK14VlmhBHjD5gg5iINO1AE73iPbrP+F1ItnmTxreEHu+VdZ6rTDkcUB36ChPVyXFS70aQo=,iv:fY1bB4ivATcptxqruqQyMIC5MNfu/fit/uB7BkV8SLg=,tag:gOdMY8CpPC+eEOW8R+1Mrw==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bnA4R01GRDA4ZXRrdDlt
        QVgwZTU2NzA2VU81YXQveGxDQ0lVSGkwaHhBCnRYaWhoQ2xtMjFQWm1xWUtkazdt
        eHZhQitKR015d3BWUGJleVpCOXJBTEEKLS0tIEs2MHlnWkQxUUVLbVRwcEFpT3Vz
        Yk9mT2tvM3RkOGZxZ2FIZmtRaUM3K0UK7Z/qmxDDZh4vIFi5MLdjiz6c+7zPf9OV
        lKq9P86D0em8bcA/ZthTk8NXcr3dFXXsQcTFO1ln8Fzob0NtLSyztg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-27T01:45:22Z"
  mac: ENC[AES256_GCM,data:ZiN4sc5nLAe8i5w4S1EsZTd3HjAsvA+0PDYkBvsDKzhcV7bZdROzwyA/3XZ3AZ59SDsRhKk1ahA2bhpMhNI6jyh5Vo+MM/mNYfqlLTW782vJMqvLmHftUvHsTFWalH/U4g87unZnVzvjYsdz2oJLyncNlfVhZDGeyoQvu6a4enQ=,iv:9+outCdVmaRi7Xqbpy/ETR1MZj7b3LXgkoh3syGU4Bw=,tag:E62MRbd3tDiQfbp6qYs3rA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
