apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
stringData:
  #ENC[AES256_GCM,data:W6HkUP/GS16HoAjyIA3lCVf3e8r5J8jsVuq4Tffh4MSYpb+45pUl8Q==,iv:BITeurJt0PkioZ3DbLSDCxF8FMgqvwK/07VXbGBrEng=,tag:7ia5dH2ItqCjyqZ4lNYAJw==,type:comment]
  HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:fP0tcjNZoUDCZ0wdy4dY6WwtPxjVVxm72v40R5+4a9o=,iv:xUGNyepcywMa++MAKNdjDBYi+v4vj1gIw6PlBbLwrzk=,tag:aGRNPajMFffNDYKVwXmAQg==,type:str]
  HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:BpQRwt9+/bmJLmF1Gv45BDW2mdjAbiQ/DFcSjOWSMmo=,iv:WgoTOF/mpkYD1647P/I9vjImTTOx9lvjPH0e6q3h9sk=,tag:6/X5q1DzuqF+HmUC5lvZRg==,type:str]
  HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:tZnTstr0Do+pTcPJYNAzYhM7KsNCzmg3F7hqaEojmZs=,iv:EfeBUahgmf0FIt6sAI34aOAsE5m0jKYZ8s5FhA+7tXU=,tag:Qawf/yAGn39fJ4KB1tNZWQ==,type:str]
  HOMEPAGE_VAR_SABNZBD_KEY: ENC[AES256_GCM,data:WeahvoWh8x5KDKzYunUhWBTPpwt0VsaTRWpZs75h+Uk=,iv:AnwgA2lglRr6rYPx7UykQiNQ/sEceYXpZcRnhIJ3zZ4=,tag:RDUIyDC0j8HOXSuArfyG0g==,type:str]
  HOMEPAGE_VAR_SEERR_KEY: ENC[AES256_GCM,data:1AFD/ZzoNXvk1oiNwqJtckEPhaPlPuJFWeoc6z2GSQ8V+L2EuD9CwYQsoNIhyMz/DFS9SDC2XQAknWOiAXn/t7fHnfQ=,iv:OOqDalyvsSFfYCrwniRqMV8x3wCy4WFh+N5Y8F9Llpw=,tag:4XHUDRFmcm/5sKs0bXXa/g==,type:str]
  #ENC[AES256_GCM,data:zWBjPfqwilfzNFLG+5xZnN/7yzflBItvANTDgrizA+U0v21VQ/+i/542iWpd2rKmigVD,iv:KmVK/gbGXWRfbzdci010ipuoPQbsW9lgq4SnwuEG7nU=,tag:HyySKLBm2boMFe6ee3TbHw==,type:comment]
  HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:utyHsLmPTqyeSg==,iv:fktvO4qxTZcr2lgH02QZLiUv75BCFbM8WCRYppqQB4A=,tag:ZUDpNe3s9JWqdgPoINwYsw==,type:str]
  HOMEPAGE_VAR_MEALIE_KEY: ENC[AES256_GCM,data:RvIN/nkGIFqZJA==,iv:4K00BB5T41fbMGVxCin5eLndKg1ro04gmeKOOv0f96E=,tag:PZHNKEO4aEm15Pf7GfUJ8g==,type:str]
  HOMEPAGE_VAR_ABS_KEY: ENC[AES256_GCM,data:Fm/nGnQkKpTMYQ==,iv:Jp6ZidbXxoJ7RsyYIu/1IumYBbeZV1Q+VocFUX/XUyw=,tag:3i+aI7wtT+IigkhK6gCQMg==,type:str]
  #ENC[AES256_GCM,data:YSLcRBor3m0s3LWWK/dYnT32WWnwjQ8w+Ul+uKPdLah9,iv:JT72XvNWRd296V0FGjwdzpIDFa/pCk1PP5rMbCRWU6Y=,tag:w4RoGDUJoE7+wm9k9vEjPA==,type:comment]
  HOMEPAGE_VAR_ADGUARD_USER: ENC[AES256_GCM,data:zqdDXg==,iv:M4t2GtmYgwECL0fAQ0mwC4+cS0KKeTVLpUrijinqNU8=,tag:Y4JLUIdf/Yw/WLgHmBSZhA==,type:str]
  HOMEPAGE_VAR_ADGUARD_PASS: ENC[AES256_GCM,data:D0axH7fysln5WfIIlaCz7OJjyzDnOWS7hUXsri5keWY=,iv:VLWjPCrzdXC5CoHflOfR4MFrq3JiC7Dbyhvc7ecAWeE=,tag:n/0I3SJGdnsTdFXy0GuxbA==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudjB4YndyUlI0Y1FvKzlW
        WCt5K25jaVVPdnI5K2krSlVud0JDMHZxTG5zClNWU0kyWndYVmtXaTZCOGJ3cFRP
        TFVYcmtsYzBORCtEZmJSS0hhYjUxQzAKLS0tIEQ2eFJQWnpTTUxNeTBmbVNwY3ds
        MDJ3dDdPK09RcGNMS1F2QlZjVWhBZGMKn+mTFwbqE7FLZymElzDibsqoJYumX/P+
        asDFgVrSIlRu1Gvn2tmy77RoJwSYPTIBCe3bpEqG7HjseuEaXN1OgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-29T20:26:53Z"
  mac: ENC[AES256_GCM,data:O4xMOlTPO0h5BP1RAshKFgInHyG4QF0Y6hkY6rA6RBVdWZop/BdfTV4425SZngxj06ZDuYrHlWBQ6tho80n59BQU9wZh2zeuVR+Csd1NZxdOGwLk0f82oonfkAURWJgXZ/4/AvDv/0tgViPD51Qkfhp6ADaJyYgzf2cw8frzsGg=,iv:wKABwNiPHmf0RbcjYzDyPHWXq6T5TBbCK2cgGaVcYGI=,tag:VJJPhRAcASA0E9gCXmB6Dw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
