apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
stringData:
  #ENC[AES256_GCM,data:ZfLGhloHJWJODBmCp9zmcRl88xdScQZXUYnb1KtQO5qt3amcYfZ84A==,iv:JebrGK1aBmdYBneMj7NbK/9TdGCA9wWrxTOVE5rz9i4=,tag:IeB0Bh42VTY9Eif4puy/sQ==,type:comment]
  HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:jhQZghsxj9yZKHbreRyvBTeBXGR3E/oPjVgmJex61kM=,iv:XR/Qaq7E8ZRa/EqlS7D2L7N75GSb5TnN0GlbZqIV5pU=,tag:sm+ea8PvbzMws5y1OLXKJw==,type:str]
  HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:JmSF2kp+0l34dRxatt+DZjrX20W8JCithonNVBNqThs=,iv:swUwzGl8Gef+uIl3FZB8+XLK1XQ1oiqQQQFTgw1cdBU=,tag:IpjrV6afz8mqCH/6tU8FXg==,type:str]
  HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:qmlrpw6SRK1GPGU4u+ze3ZlWaSaVlTenH5oVrsYDybs=,iv:X72qB1OFJedNekFxHPsoqWRaWrE/hadRn/DkwuX07LQ=,tag:b2AuPVUZrNWg2UYCYD1mvQ==,type:str]
  HOMEPAGE_VAR_SABNZBD_KEY: ENC[AES256_GCM,data:ajTPbcnnu7tLDgaYLm6Hos8go8wwdspMPBIF2SEnSwQ=,iv:whoWalL9Pfir9r0ZbwBORZe2X0oGvy6Haxd63St19ts=,tag:FtChfjiMWip1zAqovS6F9g==,type:str]
  HOMEPAGE_VAR_SEERR_KEY: ENC[AES256_GCM,data:wasbJYFD10YwQkuigqvoUW1eQTB38s9YdMDNPax3wt3C4KQpAqZzuFSc8TIZblocNdgsfgj5jQVLiAhlwErE408kc0A=,iv:/VxLDq1Dh3745cWfk11jV1S8FDOb4IBdtf0qcpkuf1I=,tag:QqGeRMDiHleTK6y7N1wcug==,type:str]
  #ENC[AES256_GCM,data:UxLhc4xgQBpcjd8D0qcGT3EbXw97TvyUk24zO/5AVxBocv443wDMp5MGqYDBZ8RbDzXL,iv:45BMaxmlKI12Jz1iqnCP1cuXD1Hi2lP6pLy31Hf+V+s=,tag:4ltWUYOhnPrV3iR7HIp4dA==,type:comment]
  HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:JAFOeIpbmnPfmThOKnTULlH8HrE5DLlafkC37UE/Xp3Ey7KKYzPwA5Dy,iv:kpRXu8Qe+olEQYJFgW6jiGcS9CbuF9J/OhI1ZjtRY+I=,tag:A94qF6oBi4UyHkmgN5Qc3A==,type:str]
  HOMEPAGE_VAR_MEALIE_KEY: ENC[AES256_GCM,data:79MotUB8uRv8iLBXbvwTPIULobt/qkNusdAE8kEG7o+dS4DJwg+rcuyjKY7qvMQA2TQ8nOYKdr61JRCz80J4EIlpo8QtK0AitKtsFY0AP3cGjl+uzm3WmOaACZbzxLZ8dXY9PwVfuMpNxqnET3CzFcaT50BN07vx5XmD5ZEKI6nrZR5yF8C0Uph8elxIV6qGizEU/JVtF2wrJrIdxWA1YHSZMlHCCBXVfh/EXR43rl+14k0DxG3vSsa+lABKIbGKizofvi4cctwovg5N5zqAn4SWyu+DrPkf7K2qLrcebI+rzK9LFkw+O/sZhcE35u0expd3ypFeL2I=,iv:KqTe/39ZRG+CNCl9mh+J4d+Vhu6lrppBInNYRNia/IA=,tag:Tmlem5uUyWOQJXsCHbCl0g==,type:str]
  HOMEPAGE_VAR_ABS_KEY: ENC[AES256_GCM,data:vjQ4VItT8P53kpU8zX1l9LV5iyGG+oFd4d9Ry1W+z0jy2QRpBTCMgCDOld3oBvd5BtA6NytqWGrKA0r0IoC4DgDZG6K9rggksgblT6Zz7+BF2vu8MMcGtNg5Q5OQHJc1eKTnPjU5MBzz5e086YEQw6wCtql6w8gI0oqPJfDI7p7+yG/MhmR7gmet2WeVDiMmEhag+7TILrF6LGDrUfo8eI8z9New+etHi94ok/t/EEzULOIoRp+dfVu1x74nIFMXI3uS0/SipW2TrbYi9QTUx7s=,iv:J0g0u27DISBGmLISGm/KN2wRWMGO47hyeO3c7GD3TGM=,tag:NTY9KMDIV8tUcbkLxPpSTQ==,type:str]
  #ENC[AES256_GCM,data:MSKM98JfOlfV2MjdjPks/uk5vaaauA+y+dJS1lIHeJygP+00Rg/RNlI=,iv:kf1WoyCebWwqLolC/kPdeN6LB88o84rDThyVRD7PHg4=,tag:ViL6z3lYQMI/ONR5qerNNw==,type:comment]
  HOMEPAGE_VAR_ADGUARD_USER: ENC[AES256_GCM,data:ibKWuA==,iv:N2T7hbkWtPj//AxF32qM5qGP6tMU6GCwzotkrlTWTIY=,tag:qz06NCajbuCY+R4TdL+DHw==,type:str]
  HOMEPAGE_VAR_ADGUARD_PASS: ENC[AES256_GCM,data:4nrAB8tRcUs8+Mp5Dn0Oh0jOXzOMWmi4adMQkyf6sf8=,iv:5S7X77v/88OWOE3Y9WQ9kDsqndoCcqD86WAMpQSOlSs=,tag:S6RlV+c9ucf6/zdw2rYdng==,type:str]
  HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:rIjNsOm01MD072KwomebPho74/c=,iv:zgPg6OHu9SsihVSij5qgJXp1MBXBQYhsKaq6G0Ottcg=,tag:t3jK5E0vRpIPmuUEnPMNbA==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFY010VGJnNTl4Qm9YdE1D
        SE45cFN6ckVEbHpCbE9PdS9ZUkR1N0VvK240ClBHS0d6bGRKdXkzcTl1cU1xMTBE
        VzN3QUMycUVwMWNJMlVqbFRlT0o4bkEKLS0tIFRzeWhtb0JjUjNSSW5nZHNRZWF4
        T3dSOEc2cmQ2T2h3czZDSUVxWFJKT3MKj015i44ZQztlUZc+alJbMdVgs2Vho2CH
        xaKrkx+5sOUWwdMCWWiZ5SJkyiKJp1L3VLxo+b97f27DBgz0xipRig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-31T00:31:38Z"
  mac: ENC[AES256_GCM,data:vK3S1auVwjPIFh0JLZPIpJrXC1a3EMOGJrkPpf8BoAqERz9XgYk9UjfkEHYnaRjnDCB0b5rGGZ3iC39cYSyP7zkltepamKbJxR4nci+cJ/eKr4wgGFB5lwwA8IwRYM7bpBQ7lmq04vhyyPTvK7AK1Xv9lVtXUZjU0K/JQJu857w=,iv:rB0P/lQ7dnbiu4hknZJM9pyMzoUoXK6RbmzM0SjuvGw=,tag:k7amFI5VfwDgE3nEsdZBcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
