apiVersion: v1
kind: Secret
metadata:
  name: smb-creds
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:vsZaH9hd7Wbs,iv:gB+C0BH8blSNRwtVTIhnTDjaQFB6XuQfeZ/7n6IlD60=,tag:lBfAadY5TTPSkYnaSPKeHQ==,type:str]
  password: ENC[AES256_GCM,data:ffhUAzzdHtQR,iv:ljDK56EPmU1q84vgTvKFeDbgFlSHshfVqOg9KE3/8a8=,tag:b8yDjhY0POjR9I3z9cy1zg==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVWpNT2hHY2Q0TW9mdDRs
        ZzJWRnZVdjBIUGE5NWpDeFl3TkpjM1hiVGhrCjFGekNreXExeVFEMjhqUFVjQTM4
        YVQ2WTg3a0twVURZYmpzQVJUeUZ1Qm8KLS0tIHhIUlplaVM1VG0yQklJNlUxcGxS
        eEkwKzBtQk0zMzdQcElvbWxCVzhJaFEK3HaZyvn+8Cga8jdRrR3ozHLY0Pv6fYZZ
        +qgPLL2O++8fa4LgL46/8xKzoyOKCCdZ9NxYzsgXpEtnL61LNzGGEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-28T17:07:03Z"
  mac: ENC[AES256_GCM,data:z8HKEiaARtohGZ4i69EtBYCvxtbO5mQ9hEe9kjRo9b1VcpgUZ29PtECyiVKLsxdLX1ozk0X29Gn5Vis4XeHUUM5yXgMy0gsS41zLi7tkA/WXLWl1g0QwtJ/qUgWK9FT+k06F1RG5d4qV35mSHm68YHDkRcMg+V9NhYaQJk006a4=,iv:SEm0kiIfXkxslY6MvFR+nqHIKXNYv1YEa0JJDwvCbQU=,tag:zmoWpVGeyTy9tGg2jmpgXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
