apiVersion: v1
kind: Secret
metadata:
  name: jellyplex-watched-secret
type: Opaque
stringData:
  PLEX_TOKEN: ENC[AES256_GCM,data:YySAD2D1UUsIeEz1d8gHCqYehXE=,iv:EaCwCFuUewjz5o6BNZT025ig3jtFSkbyYEaB8R30y0A=,tag:ojRa7QaO/4APn4mntk9TZQ==,type:str]
  JELLYFIN_TOKEN: ENC[AES256_GCM,data:pG+AMblo/Y+SKEJz0CGYGknaqDIMSQLNqSzj9erpjrQ=,iv:trgUxyIVFxj5hzt1q5fWLA8n9h/L+h1CukPotAAGyEw=,tag:Y5KYOrAJgt6GghjRU0RrXw==,type:str]
sops:
  age:
    - recipient: age1lrc9kshjxwgx4q6zpq0xkm6mcux6qn5pkdfh27kzwl30g6hl6gdsj2rcfw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdi9ha1M1QlRINU9LN1Ns
        d0VpbEV0RThMbUt5RlVJK0dnelFST1lmb0JFCmdLdVBTa1l6L0gwZzU5STRiajBK
        T2M5c0RDZU0zMTRRSW0wa3ArdUdZVDgKLS0tIDE4Njh4M2lNVlhKWGV6Q0FCQkRk
        ZHR2aGNwYmRGOU92UzJSQmxtVk81MmMKJAcoj7fN/Ri7QDBKulrKs0GCar0zKCPZ
        i0s45eH8ootOIKQdm04v6kpsycM9XG5KDD5XnJ9I2+saPP8471ax8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-05T18:22:22Z"
  mac: ENC[AES256_GCM,data:xay0F/Lu6owBW8otyp8BqXuY7FnlT37GhaYQL9HB7Xffr/jE3V5a2N/POsVJW+jPL0dGft0hpffDGfD8vO1h0pBR31VxprxUb92t2hGtCZZuTtOAaatIyFSPwXFw4VAWWR5YAQRG9ZTzoFNKY6bYJb5LC+sw7VysstXiCNkfVXM=,iv:NrZgIrrSCPwy6Yg/8zU/wz2mdHbEvsrVtpUCIw4nrgE=,tag:w7BNiFD0RjrxHEslcrCzEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
